blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://discord.gg/JuFDMrTRSD # TODO update with chat.nimbus.town later
    about: Ask questions and discuss with other users in real time.
  - name: Questions & Discussions
    url: https://github.com/tsky-dev/tsky/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
